name: Fly Prod API Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    concurrency: deploy-group
    permissions:
      contents: read
      deployments: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy if API was affected
        run: flyctl deploy --no-cache --config ./fly.prod.toml --dockerfile ./Dockerfile.api.prod
        env:
          FLY_API_TOKEN: ${{secrets.FLY_PROD_API_TOKEN}}
